### ISSUE TITLE
urllib.error.URLError

### ISSUE THREAD

**Issue by nivaca** [stenskjaer/lbp_print#2]
Hi Michael,

I get the following output when installed and run as you instruct (Mac OS, Python 3.6):

```SH
~/Downloads/lbp_print(branch:master) » ./lbp_print.py pdf --scta http://scta.info/resource/lectio1
DEBUG: {'--help': False,
 '--local': False,
 '--output': None,
 '--scta': True,
 '--verbosity': None,
 '--version': False,
 '--xslt': None,
 '--xslt-parameters': None,
 '<expression-id>': 'http://scta.info/resource/lectio1',
 '<file>': None,
 'pdf': True,
 'tex': False}
INFO: App initialized.
INFO: Logging initialized.
INFO: Remote resource initialized.
WARNING: The supplied download directory download does not exist. It will be created.
INFO: Downloading remote resource...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lbp_print.py", line 336, in <module>
    transcription = RemoteTranscription(args["<expression-id>"])
  File "./lbp_print.py", line 123, in __init__
    self.file = self.__define_file()
  File "./lbp_print.py", line 156, in __define_file
    with urllib.request.urlopen(self.transcription_object.resource().file().file().geturl()) as response:
  File "/Volumes/ElDuro/nivaca/Downloads/lbp_print/src/lbppy/lbppy/file.py", line 17, in file
    response = urllib.request.urlopen(self.file_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
(lbp_print) --
```

I have created an SSH key for Github and Bitbucket.

**Comment by stenskjaer** [comment]
Have you seen this: https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c?
It seems to be a OS X vs Python 3.6 problem. Is your Python the official distribution installation? If it is, the "Install Certificates.command" should be available to you as indicated in the SE answer. That is my first guess.

My Homebrew installation does not suffer from this problem (and I also do not have the Python 3.6 application directory from the SE answer).

I wonder whether this is going to be a general problem to most. It looks like there is a risk of that...

Edit: Another SE post (https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c) pointed out the following commands or options:

> Run in terminal:
> `/Applications/Python 3.5.2/Install Certificates.command`
> or update certifi package via pip

See the Python issue ticket for more info: https://bugs.python.org/issue28150

**Comment by nivaca** [comment]
Hi Michael,
I finally managed to install it and make it work in one of my Linux machines (a Manjaro one). I had no problems there. I don't have my Macbook here, so I cannot test the recommended solution you gave.
Anyways, I have a couple of questions:

- Why did you use the XeLaTeX engine? I think plain old LaTeX will suffice. Or better, if you want to use polyglossia, LuaLaTeX, which I think is far superior to XeLaTeX.
- Why do you recommend `mkvirtualenv`? I would normally use: `python3.6 -m venv lbp_print`.

Cheers,
Nick

**Comment by stenskjaer** [comment]
About xelatex: I generally experience that it compiles the pdf much faster than lualatex. The advantages of lualatex (in particular the superior programming interface) is not called for in this context. I prefer xelatex over latex handling unicode is simpler. If you can provide a better (faster, simpler, or with fewer dependencies) solution, I am all ears! 

About mkvirtualenv: That is a matter of personal preference, I think. I don't necessarily recommend that over venv, as I just refer to the guide on the Hitchhiker's guide, but I personally prefer having the environments out of the local directory.
(I would be happy to talk about these things more, if you think. Maybe make another issue to keep it separate from this, or take it up in Slack)

Let me know when you get a chance to see if the links above solve you problem on the Mac.

(Another thing: If you have improvements or things you feel are missing from the readme, of course I can improve it myself, but pull requests are of course also welcome!) 

Cheers!
